# Generated by Django 2.1.4 on 2018-12-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_index_overlay_and_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='button_hover',
            field=models.CharField(default='#ba7c37', max_length=7),
        ),
    ]
