# Generated by Django 2.1.4 on 2018-12-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_index_button_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='background_media',
            field=models.FileField(default='bg.mp4', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='index',
            name='button_hover',
            field=models.CharField(default='#ba7c37', max_length=30),
        ),
        migrations.AlterField(
            model_name='index',
            name='overlay_and_button_color',
            field=models.CharField(default='#cd9557', max_length=30),
        ),
    ]
