# Generated by Django 2.1.4 on 2018-12-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_auto_20181225_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='media_position_left',
            field=models.CharField(default='50%', max_length=10),
        ),
        migrations.AddField(
            model_name='index',
            name='media_position_top',
            field=models.CharField(default='50%', max_length=10),
        ),
    ]
