# Generated by Django 2.1.4 on 2018-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_auto_20181225_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='background_and_icon_color',
            field=models.CharField(default='rgba(0,46,102,.8)', max_length=30),
        ),
        migrations.AddField(
            model_name='index',
            name='background_and_icon_color_color',
            field=models.CharField(default='#002e66', max_length=30),
        ),
    ]
