# Generated by Django 2.1.4 on 2018-12-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_auto_20181225_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='background_and_icon_color_color',
            new_name='background_and_icon_hover_color',
        ),
    ]
