# Generated by Django 2.1.4 on 2018-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_auto_20181225_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='user_status',
            field=models.CharField(default='Inactive', max_length=7),
        ),
    ]
