# Generated by Django 2.1.4 on 2018-12-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_index_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('requirmebts', models.TextField(max_length=400)),
                ('site_name', models.CharField(max_length=100)),
                ('site_link', models.CharField(max_length=500)),
                ('background_media', models.FileField(default='Capture.PNG', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Index'),
        ),
    ]
