# Generated by Django 2.1.4 on 2018-12-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_auto_20181225_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDetail',
            new_name='Project',
        ),
    ]
