# Generated by Django 2.1.4 on 2018-12-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_auto_20181225_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='background_media',
            new_name='media',
        ),
    ]
