# Generated by Django 2.1.4 on 2018-12-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_auto_20181225_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='requirmebts',
            new_name='requirments',
        ),
        migrations.AlterField(
            model_name='index',
            name='user_status',
            field=models.CharField(default='Inactive', max_length=8),
        ),
    ]
