# Generated by Django 2.1.4 on 2018-12-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_auto_20181226_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
