# Generated by Django 2.1.4 on 2018-12-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0017_project_site_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='site_link_icon',
            field=models.CharField(default='<i class="fas fa-eye"></i>', max_length=500),
        ),
    ]
