# Generated by Django 2.1.4 on 2018-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_auto_20181227_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index page'},
        ),
    ]
