# Generated by Django 2.1.4 on 2018-12-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_auto_20181227_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('name', models.TextField(max_length=400)),
                ('email', models.TextField(max_length=400)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('site_link', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Index')),
            ],
        ),
    ]
