# Generated by Django 2.1.4 on 2018-12-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0020_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
