# Generated by Django 2.1.4 on 2018-12-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0021_auto_20181228_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=400)),
                ('email', models.TextField(max_length=400)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('site_link', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Index')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='site_link',
            new_name='button_color',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='button_text',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
