# Generated by Django 2.1.4 on 2018-12-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0023_auto_20181228_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
