# Generated by Django 2.1.4 on 2018-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0024_application_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon_color',
            field=models.CharField(default='rgba(0,46,102,.8)', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='icon_hover_color',
            field=models.CharField(default='#002e66', max_length=30),
        ),
    ]
