# Generated by Django 2.1.4 on 2018-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0025_auto_20181228_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='footer',
            field=models.CharField(default='Copyright &copy; ashikunnabi.pythonanywhere.com | 2018', max_length=10),
        ),
    ]
