# Generated by Django 2.1.4 on 2018-12-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0027_auto_20181229_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
