# Generated by Django 2.1.4 on 2018-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0028_auto_20181231_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
