# Generated by Django 2.1.4 on 2018-12-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='last_name',
        ),
    ]
