# Generated by Django 2.1.4 on 2018-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_remove_experience_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetail',
            name='picture',
            field=models.FileField(default='Capture.PNG', null=True, upload_to=''),
        ),
    ]
